### ISSUE TITLE
A question about eclat algorithm?

### ISSUE THREAD

**Issue by dsj96** [DandelionLau/MachineLearning#3]
When I run the ECLAT_TEST.py file,  I want to  konw waht's the mining of  "1" in the result 
`Association Rules:
(frozenset(['bread']), frozenset(['milk']), 1)
(frozenset(['milk', 'bread']), frozenset(['eggs']), 1)
...`
I would be very grateful if I could get your reply.

**Comment by Ryuk17** [comment]
The output is a tuple, (X, Y, confidence),  the confidence is calculated at [https://github.com/Ryuk17/MachineLearning/blob/e3a75d787078da2a03ca1b824a0c319e3020a4cd/AssociationAnalysis.py#L520](url)
